### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by Shelfcol** [zju3dv/street_crafter#1]
Brilliant work in this paper!
There is a question: In the implementation detail, you say It takes 2 days to train the model on 8 NVIDIA A800 80GB GPUs to train Unet, and 1.5 hours on one A800 GPU during the distillation process from StreetCrafter to 3DGS. Does every case need two steps above, which seems resource-consuming?

**Comment by yunzhiy** [comment]
Hi, thanks for your interest. StreetCrafter only needs to be trained once and can be generalized to all sequences without per-scene optimization (Ours-V in the paper). If real-time inference is required, it takes about 1.5 hours to distill the generative prior into the dynamic 3DGS representation for each sequence (Ours-G in the paper).

**Comment by Shelfcol** [comment]
Oh, I see, thank you.
Have you ever tried to use stable diffusion+controlnet(image-to-image)? Like given one case, use it to finetune model, then infer with rendering result of 3dgs in novel view, just like your StreetCrafter? Vista is video generation,while SD is image generation.



---Original---
From: "Yunzhi ***@***.***&gt;
Date: Wed, Dec 25, 2024 20:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zju3dv/street_crafter] Training time (Issue #1)




 
Hi, thanks for your interest. StreetCrafter only needs to be trained once and can be generalized to all sequences without per-scene optimization (Ours-V in the paper). If real-time inference is required, it takes about 1.5 hours to distill the generative prior into the dynamic 3DGS representation for each sequence (Ours-G in the paper).

**Comment by yunzhiy** [comment]
We have tried to reduce the number of frames of the video model (as small as 3 frames), which leads to a decrease in FID of both Ours-v and Ours-G. I think generating novel views with video model can help maintain temporal consistency and leads to better performance.
Moreover, stable diffusion+controlnet(image-to-image) may fail to generate pausible results under regions without LiDAR condition due to lack of reference image. Some other types of pixel-level condition may be more suitable such as degraded rendering results as in one of the recent works [FreeSim ](https://arxiv.org/abs/2412.03566).

**Comment by Shelfcol** [comment]
Thank you for your reply. Stable Video Diffusion actually keeps the temporal consistency. FreeVS also use SVD.
Also looking forward to your code release for testing.
